#!/bin/bash
#########################################################
# Function :快速创建node项目                              #
# Platform :All Linux Based Platform                    #
# Version  :1.0                                         #
# Date     :2022-08-04                                  #
# Author   :zhangdexian                                 #
#########################################################

function echo_color() {
    if [ $2 == "green" ]; then
        echo -e "\033[32;40m$1\033[0m"
    elif [ $2 == "red" ]; then
        echo -e "\033[31;40m$1\033[0m"
    fi
}

if [ -z "$1" ]; then
    echo_color "请输入项目名称" red
    exit 1
fi

if [ -f "$1" ]; then
    echo_color "项目已存在" red
    exit 1
fi

dirname=$1

echo_color "正在创建项目 $dirname" green
mkdir -p "$dirname"
cd "$dirname" || exit 1

echo_color "正在初始化npm" green
npm init -y

echo_color "正在安装依赖" green
pnpm add typescript @types/node --save-dev

echo_color "正在初始化typescript" green
npx tsc --init

echo_color "项目创建完成" green

sleep 1

code .
